<?php

/**
 * DynCatsMenu
 * 
 * NOTICE OF LICENSE 
 * 
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE (Version 3)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl.html
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to red331@mail.ru so we can send you a copy immediately.   
 *  
 * author      Selihov Sergei Stanislavovich <red331@mail.ru>, Valentin Belyakov <nipellio@gmail.com> 
 * copyright   Copyright (c) 2010-2011 Selihov Sergei Stanislavovich.
 * license     http://www.gnu.org/licenses/gpl.html  GNU GENERAL PUBLIC LICENSE (Version 3)
 *    
 */
 
  
if ($this->box->cattree == false) {return false;}
$this->headLink()->appendStylesheet('skin/front/fallback/dyncatsmenu/css/style.css');
$this->box->ShowCats($this->box->cattree, $this);

?>

<script type="text/javascript">

$('.DCMContOut li a').bind('click', function(event)
	{
  event.stopPropagation()
	});

$('.DCMContOut li').bind('click', function(event)
	{
	event.stopPropagation();
	if ($(this).attr('class').indexOf('DCMNotShow') != -1)
		{
		$(this).addClass('DCMShow');
		$(this).removeClass('DCMNotShow');
		}
	else
		{
		$(this).addClass('DCMNotShow');
		$(this).removeClass('DCMShow');
		}
	});

</script>